<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class VitalStat extends Model
{
    use HasFactory;

    protected $fillable = ['week_number',
                            'store_id',
                            'year',
                            'STORENAME', 
                            'MANAGER', 
                            'PR_WK_COR', 
                            'CUR_WK_COR', 
                            'STRE_OPEN_DATE', 
                            'WKS_OPEN', 
                            'ANDER_EQUIV', 
                            'ANDER_PCT_COMP', 
                            'WK_PAY_OFF', 
                            'CUST_RENT', 
                            'new_agr', 
                            'CASH_SALES', 
                            'SERVICE_REVENUE', 
                            'PCT_MARGIN', 
                            'PCT_CUST_RENT', 
                            'PCT_CUST_RENT_YEAR', 
                            'AVG_TURN', 
                            'SAT_CLOSE', 
                            'SAT_CLOSE_7', 
                            'SAT_CLOSE_14', 
                            'SAT_CLOSE_21', 
                            'SAT_CLOSE_30', 
                            'SAT_CLOSE_OVR30', 
                            'SKIPS', 
                            'SKIP_RATIO', 
                            'SKIP_RATIO_MONTH', 
                            'REPOS', 
                            'ALIGN_PCT', 
                            'NEWALIGN_PCT', 
                            'autopay_pct', 
                            'NEW_AUTOPAY_PCT', 
                            'AGR_LDW_PCT', 
                            'AGR_CLUB_PCT', 
                            'agr_newclub_pct', 
                            'INV_PURCH_LW', 
                            'INV_SOLD_LW', 
                            'TOT_IDLE_INV', 
                            'PCT_IDLE_USED', 
                            'IDLE_OVER_45', 
                            'IDLE_OVER_90', 
                            'IDLE_OVER_180', 
                            'PCTFREETIME', 
                            'TOT_ADV_PAY', 
                            'NEG_PYMT', 
                            'AVG_ITEM_AGR', 
                            'AVG_AGR_CUST', 
                            'DUP_CUST', 
                            'FREEDAYS', 
                            'WK_PROMO_DOLLARS', 
                            'WK_PROMO_CUSTS', 
                            'PROMO_CUST_RENT_RATIO', 
                            'WK_AVG_PROMO_CUST', 
                            'AVG_WKS_TO_PO', 
                            'PCT_WITH_INSPECTION', 
                            'PCT_ESTIMATE', 
                            'PCT_CONVERSION', 
                            'PR_WK_SOR', 
                            'CUR_WK_SOR', 
                            'WK_SVC_PAYOFF', 
                            'WK_SVC_SKIP', 
                            'SVC_WK_REV', 
                            'SVC_CASH_SALES', 
                            'SVC_SAT_CLOSE', 
                            'SVC_SAT_CLOSE_7', 
                            'SVC_SAT_CLOSE_14', 
                            'SVC_SAT_CLOSE_21', 
                            'SVC_SAT_CLOSE_30', 
                            'SVC_SAT_CLOSE_OVR30', 
                            'NUMOVERRIDES', 
                            'OVERRIDEAMT', 
                            'NUMDISPOSED', 
                            'NUMMISCEXP', 
                            'MISCEXPAMOUNT', 
                            'NUMMISCCLUB', 
                            'TPMSCOUNTSALES', 
                            'TPMSSALEAMT', 
                            'AOR'];
}
